name: Repo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  debian-repo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build the repo
        run: ./build ostreeRepo-${{ matrix.arch }}
        working-directory: ./debian
      - name: Upload ${{ matrix.arch }} repo
        uses: actions/upload-artifact@v3
        with:
          name: ostree-${{ matrix.arch }}-trixie-repo
          path: debian/.build/ostreeRepo-${{ matrix.arch }}-trixie*.ostreeRepo.tar.gz
          retention-days: 2

  gardenlinux-repo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, arm64 ]
        platform: [ kvm, metal ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build the repo
        run: ./build ${{ matrix.platform }}_dev_curl-ostreeRepo-${{ matrix.arch }}
        working-directory: ./gardenlinux
      - name: Upload ${{ matrix.arch }} repo
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}_dev_curl-ostreeRepo-${{ matrix.arch }}
          path: gardenlinux/.build/${{ matrix.platform }}*${{ matrix.arch }}*.ostreeRepo.tar.gz
          retention-days: 2
